export enum Fonts {
  Regular = 'Regular',
  Medium = 'Medium',
  Bold = 'Bold',
  IconsFont = 'Material',
  Light = 'Font-Light',
  ExtraLight = 'Font-ExtraLight',
}

export enum Colors {
  black = '#000',
  white = '#FFF',
  dark = '#1C3E60',
  lightGray = '#F8F6F6',
  darkGray = '#414141',
  gray = '#676767',
  blue = '#2D637F',
  blue2 = '#376EA6',
  lightBlue = '#4097C3',
  lightBlue2 = '#89AABB',
  lightBlue3 = '#F2F6FA',
  complementary = '#F5A623',
  lightGray2 = '#EEEEEE',
  red = '#D0021B',
  redLight = '#d07e80',
  yellow = '#F8E71C',
  lightGray3 = '#FBFBFB',
  lightGray4 = '#F8F8F8',
  green = '#7ED321',

}

export enum FontSizes {
  title = 18,
  normal = 16,
  small = 14,
  smaller = 12,
  tiny = 10,
}

export enum Icons {
  menu = '\uf197',
  tvPlay = '\uf2db',
  calendarAlt = '\uf32e',
  viewList = '\uf320',
  playCircle = '\uf3a9',
  chevronLeft = '\uf2fa',
  chevronDown = '\uf2f9',
  chevronUp = '\uf2fc',
  chevronRight = '\uf2fb',
  time = '\uf337',
  pin = '\uf1ab',
  squareCheck = '\uf26a',
  squareOutline = '\uf279',
  close = '\uf136',
  dotCircle = '\uf26f',
  viewListAlt = '\uf31f',
  circleCheck = '\uf269',
  circleOutline = '\uf26c',
  circle = '\uf26d',
  star = '\uf27d',
  starHalf = '\uf27b',
  starOutline = '\uf27c',
  wrench = '\uf1ed',
  navigation = '\uf1a1',
  commentTextAlt = '\uf262',
  plus = '\uf278',
  edit = '\uf158',
  delete = '\uf154',
  caretDown = '\uf2f2',
  check = '\uf26b',
  camera = '\uf28c',
  cameraAdd = '\uf283',
  mailSend = '\uf194',
  refresh = '\uf1b9',
  search = '\uf1c3',
  account = '\uf207',
  lock = '\uf191',
  key = '\uf183',
  forward = '\uf2fd',
  email = '\uf15a',
  undo = '\uf258',
  archive = '\uf105',
  assignmentAccount = '\uf106',
  minusCircle = '\uf271',
  plusCircle = '\uf276',
  plusCircleOutline = '\uf275',
  chart = '\uf131',
  assignment = '\uf10c',
  phone = '\uf2be',
  phoneInTalk = '\uf2b6',
  collectionImageFolder = '\uf13e',
  caretUpCircle = '\uf2f7',
  caretUp = '\uf2f8',
  alertCircleOutline = '\uf1f0',
  alertCircle = '\uf1f1',
  comments = '\uf266',
}
